# Generated by Django 3.1.2 on 2022-01-30 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Dashboard Name')),
                ('dashboard_url', models.CharField(max_length=250, unique=True, verbose_name='Dashboard URL')),
                ('thumbnail_url', models.CharField(max_length=250, verbose_name='Thumbnail URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Public Dashboard',
                'verbose_name_plural': 'Public Dashboards',
            },
        ),
    ]
