# Generated by Django 3.1.2 on 2022-03-29 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('otp_code', models.CharField(max_length=6, verbose_name='OTP Code')),
                ('verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('last_otp_time', models.DateTimeField(auto_now=True, verbose_name='Last OTP time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'PasswordReset',
                'verbose_name_plural': 'PasswordResets',
            },
        ),
    ]
