# Generated by Django 3.1.2 on 2022-03-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'verbose_name': 'Password Reset', 'verbose_name_plural': 'Password Resets'},
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
