# Generated by Django 3.1.2 on 2022-03-31 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220329_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^\\+(?:[0-9] ?){6,14}[0-9]$')]),
        ),
    ]
